### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by closca** [flashphoner/flashphoner_client#5]
Any plan for typescript typings?
Would be really nice to have those when people try to use the client into a typescript web app.

Thanks,
Costel.

**Comment by flashphoner** [comment]
Currently we do not have nearest plans to rewrite our Web SDK API using typescript.
As we know, typescript can use JavaScript calls, isn't it?

Could you please describe in detail what troubles do you have using our API from typescript?
Or is it totally impossible?

**Comment by closca** [comment]
Actually works pretty good. We integrated with Angular 4 which is in typescript and I am really happy.
You don;t need to rewrite in typescript. Just to generate .d.ts file with typings. Is really helpful for developing. https://www.npmjs.com/package/generator-typings <https://www.npmjs.com/package/generator-typings>


Thanks,
Costel.

**Comment by flashphoner** [comment]
We will look at this.
Thanks.

**Comment by EvK** [comment]
Any updates on this issue? It's very convenient to have typescript typings for type safety, intellisense and such things. I'm going to integrate flashphoner with a big application developed in typescript, but can't really let it be the only part of application which is not type safe.

**Comment by flashphoner** [comment]
We raised internal ticket (WCS-2382) on this issue, but this supposed to be implemented in next major WebSDK version

**Comment by sapter** [comment]
Any updates on this?

**Comment by flashphoner** [comment]
> Any updates on this?

No updates yet. We raised tickets WCS-2382 priority and will add types description to [official NPM package](https://www.npmjs.com/package/@flashphoner/websdk).

**Comment by flashphoner** [comment]
We added Typescript typing since build [2.0.203](https://flashphoner.com/downloads/builds/flashphoner_client/wcs_api-2.0/flashphoner-api-2.0.203-d9abaca755dff40816352fe162459cb3b6f4c6aa.tar.gz). Please read [React application in Typescript example description](https://docs.flashphoner.com/display/WEBSDK2EN/Two+Way+Streaming+in+Typescript) and check its [source code](https://github.com/flashphoner/flashphoner_client/blob/4b9703687aab251d0d6b618eaac6ba677bdd1aef/examples/typescript/two-way-streaming-ts)
